version: '3'
services:
  master:
    container_name: master
    hostname: master
    image: "grubykarol/locust:0.13.5-python3.8-alpine3.11"
    environment:
      ATTACKED_HOST: http://example.com
      LOCUST_MODE: master
      LOCUST_MASTER_BIND_PORT: 5557
      TASK_DELAY_FROM: 5
      TASK_DELAY_TO: 30
      QUIET_MODE: "${QUIET_MODE:-false}"
      LOCUST_OPTS: "--no-web --expect-slaves 1 -c 1 -r 1 -t 10s"
    volumes:
      - ./locust-scripts:/locust

  slave:
    image: "grubykarol/locust:0.13.5-python3.8-alpine3.11"
    environment:
      ATTACKED_HOST: http://example.com
      LOCUST_MODE: slave
      LOCUST_MASTER_HOST: master
      LOCUST_MASTER_BIND_PORT: 5557
      NO_PROXY: master
      TASK_DELAY_FROM: 5
      TASK_DELAY_TO: 30
      QUIET_MODE: "${QUIET_MODE:-false}"
      LOCUST_OPTS: "--no-web"
    volumes:
      - ./locust-scripts:/locust
